name: Build and deploy docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Get info
        run: |
          echo "---------------------"
          echo "$USER"
          echo $PWD
          echo "---------------------"
      - name: Build docker images
        run: docker compose build

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Get info
        run: |
          echo "---------------------"
          echo "$USER"
          echo $PWD
          echo "---------------------"
      - name: Run docker images
        run: docker compose up -d
